### ISSUE TITLE
the importation of data from the new Prisma 3T does not work

### ISSUE THREAD

**Issue by toniomoreno** [neurospin/unicog#10]
In file "import_and_convert_dicom.py" there is no possibility to choose the Prisma 3T scanner, only the TrioTim is used by default.

This is the error message I have:
>>python import_scans.py scan_list.txt 
Reading scans list scan_list.txt
fetching scans
 ! WARNING: this path doesn't exist /neurospin/acquisition/database/TrioTim/20170221/lk160274*/16
 ! WARNING: this path doesn't exist /neurospin/acquisition/database/TrioTim/20170221/lk160274*/05
 ! WARNING: this path doesn't exist /neurospin/acquisition/database/TrioTim/20170221/lk160274*/07
 ! WARNING: this path doesn't exist /neurospin/acquisition/database/TrioTim/20170221/lk160274*/09
 ! WARNING: this path doesn't exist /neurospin/acquisition/database/TrioTim/20170221/lk160274*/13
 ! WARNING: this path doesn't exist /neurospin/acquisition/database/TrioTim/20170221/lk160274*/15
 ! WARNING: this path doesn't exist /neurospin/acquisition/database/TrioTim/20170221/lk160274*/17
 ! WARNING: this path doesn't exist /neurospin/acquisition/database/TrioTim/20170221/lk160274*/19
 ! WARNING: this path doesn't exist /neurospin/acquisition/database/TrioTim/20170221/lk160274*/23
Converting dicoms to nifti

**Comment by isadenghien** [comment]
Hi, 
You're right. One option is missing now.
The code would be fixed with something like that:
if scanner == "3T_trio":
scanner_name = "TrioTim"
elif scanner == "3T_prisma":
scanner_name == "<name_directory_for_prisma>
....

But you can try the first version of BIDS available in the repository.
