### ISSUE TITLE
neurospin_to_bids.py produces duplicate rows in participants.tsv

### ISSUE THREAD

**Issue by ylep** [neurospin/unicog#13]
When importing longitudinal data (multiple sessions for each subject), `neurospin_to_bids.py` produces duplicate rows in participants.tsv, which is forbidden by BIDS:

> Each participant MUST be described by one and only one row.

**Comment by isadenghien** [comment]
Ok, thanks. I'm going to fix it.

**Comment by isadenghien** [comment]
Fix.
see https://github.com/neurospin/unicog/commit/19694cab4ef71be1d05de25358f24cc370540b9c
