### ISSUE TITLE
how to add a level session in the participants.tsv

### ISSUE THREAD

**Issue by isadenghien** [neurospin/unicog#5]
Hi, 

If you want to import a level session, how to modify the participants.tsv file:

1st proposition:
         participant_id	NIP	acq_date
        sub-1-ses-1 	nip_number	2010-06-28
        sub-1-ses-2 	nip_number	2010-06-25
        sub-2-ses-1	nip_number	2010-07-01
        sub-2-ses-2	nip_number	2010-05-23

2nd proposition:
         participant_id	session    NIP	acq_date
        sub-1       ses-1 	nip_number	2010-06-28
        sub-1       ses-2 	nip_number	2010-06-25
        sub-2       ses-1	nip_number	2010-07-01
        sub-2       ses-2	nip_number	2010-05-23

I didn't see this kind of information in the Bids specification. Not sure if it possible to add a field in the participants.tsv ?

Any idea ?

Isa

**Comment by MartinPerez** [comment]
@isadenghien  its already possible. I will create an example in a coming PR then.

**Comment by MartinPerez** [comment]
I added some quick comments on this in the #6 review

**Comment by isadenghien** [comment]
Hi, 
Ok the solution is a specific field is already designed on the first line of the participants.tsv file like: 

participant_id session_id session NIP acq_date

Isa

**Comment by MartinPerez** [comment]
The solution is two things:

1) As you mention to add the session_id field to participants.tsv
2) That the download file reflects in the filename session if necessary like "ses-01_download"
